### ISSUE TITLE
How to configure Cassandra with Pyramid.

### ISSUE THREAD

**Issue by Aravindpogu** [EnigmaCurry/cassandra-playground#1]
I've a requirement to develop a web app using pyramid and cassandra in the back end. I've googled enough to find out how to configure cassandra in pyramid (using alchemy scaffold). But, I could not find much details on the same. As per my search, I found that it is not possible to configure NoSQL class databases using alchemy. Is there any way to integrate cassandra with pyramid.

**Comment by EnigmaCurry** [comment]
I would use the DataStax driver and it's [Object Mapper support](http://datastax.github.io/python-driver/object_mapper.html). This repository is REALLY old, so don't use any of the code here.

**Comment by EnigmaCurry** [comment]
You might also check out how I [do this in cstar_perf](https://github.com/datastax/cstar_perf/blob/master/frontend/cstar_perf/frontend/server/model.py) which is a flask application. But, if I were to rewrite that file today, I'd probably use the Object Mapper above.

**Comment by Aravindpogu** [comment]
Thanks.. It is very helpful to grasp some idea..
